### ISSUE TITLE
`xattr: No such file` when `HOMEBREW_CASK_OPTS` is set

### ISSUE THREAD

**Issue by cpressland** [nikitabobko/homebrew-tap#2]
During the installation of AeroSpace I see the following output:

```
==> Installing Cask aerospace
==> Moving App 'AeroSpace.app' to '/Users/cpressland/Applications/AeroSpace.app'
==> Linking Binary 'aerospace' to '/opt/homebrew/bin/aerospace'
<snipped>
xattr: No such file: /Applications/AeroSpace.app
🍺  aerospace was successfully installed!
```

I'm using the `HOMEBREW_CASK_OPTS=--appdir=~/Applications` environment variable which is likely the cause of this. Can the install script be updated to respect this variable? I'm not directly familiar with Homebrews backend, but happy to figure out the correct incantation.

Looks like this is the culprit:
https://github.com/nikitabobko/homebrew-tap/blob/main/Casks/aerospace.rb#L17

**Comment by nikitabobko** [comment]
Thanks, should be fixed now
